# Generated by Django 3.0.4 on 2020-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('mobile', models.CharField(default='', max_length=100)),
                ('housename', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
