# Generated by Django 3.0.4 on 2020-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('commonName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('productType', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='product/images')),
            ],
        ),
    ]
