# Generated by Django 3.0.4 on 2020-04-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_auto_20200415_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('applicationId', models.AutoField(primary_key=True, serialize=False)),
                ('applicationName', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('requirement1', models.CharField(default='', max_length=100)),
                ('requirement2', models.CharField(default='', max_length=100)),
                ('requirement3', models.CharField(default='', max_length=100)),
                ('requirement4', models.CharField(default='', max_length=100)),
                ('applicationNotice', models.FileField(default='', upload_to='application/documents')),
                ('applicationForm', models.FileField(default='', upload_to='application/documents')),
            ],
        ),
    ]
