# Generated by Django 3.0.4 on 2020-05-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationNotice',
            field=models.ImageField(default='', upload_to='application/documents'),
        ),
    ]
