# Generated by Django 3.0.4 on 2020-05-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0005_auto_20200503_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationNotice',
            field=models.ImageField(default='', upload_to='application/documents'),
        ),
    ]
