# Generated by Django 3.0.4 on 2020-05-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_auto_20200503_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='application',
            new_name='aplications',
        ),
    ]
