# Generated by Django 3.0.4 on 2020-05-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0007_auto_20200503_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aplications',
            new_name='applications',
        ),
    ]
