# Generated by Django 3.0.4 on 2020-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0009_auto_20200503_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='technique',
            fields=[
                ('techniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('techniqueName', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('video', models.FileField(default='', upload_to='techniques/videos')),
            ],
        ),
    ]
