# Generated by Django 3.0.4 on 2020-05-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0010_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
