# Generated by Django 3.0.4 on 2020-04-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
